name: Apply labels to PR
on:
  pull_request_target:
    types: [opened, reopened, synchronize]

permissions:
  contents: read

jobs:
  pr-labeler:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Label PR
        uses: release-drafter/release-drafter@v6.1.0
        with:
          config-name: pr-labeler.yml
          disable-autolabeler: true
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
